extends: "spectral:oas"
rules:
  operation-description:
    description: "Operations must have a description"
    severity: warn
    given: "$.paths[*][*]"
    then:
      field: description
      function: truthy